/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of: https://github.com/facebook/docusaurus
 */

type Optional<T extends object, K extends keyof T = keyof T> = Omit<T, K> &
  Partial<Pick<T, K>>;

type Expand<T extends { [x: string]: unknown }> = { [P in keyof T]: T[P] };

export type SidebarItemBase = {
  key?: string;
  className?: string;
  customProps?: { [key: string]: unknown };
};

export type SidebarItemDoc = SidebarItemBase & {
  type: "doc" | "ref";
  label?: string;
  id: string;
  /**
   * This is an internal marker set during the sidebar normalization process.
   * Docs with labels defined in the config need to be translated with JSON.
   * Otherwise, it's preferable to translate the MDX doc title or front matter.
   */
  translatable?: true;
};

export type SidebarItemHtml = SidebarItemBase & {
  type: "html";
  value: string;
  defaultStyle?: boolean;
};

export type SidebarItemLink = SidebarItemBase & {
  type: "link";
  href: string;
  label: string;
  autoAddBaseUrl?: boolean;
  description?: string;
};

export type SidebarItemAutogenerated = SidebarItemBase & {
  type: "autogenerated";
  dirName: string;
};

type SidebarItemCategoryBase = SidebarItemBase & {
  type: "category";
  label: string;
  collapsed: boolean;
  collapsible: boolean;
  description?: string;
};

export type SidebarItemCategoryLinkDoc = { type: "doc"; id: string };

export type SidebarItemCategoryLinkGeneratedIndexConfig = {
  type: "generated-index";
  slug?: string;
  title?: string;
  description?: string;
  image?: string;
  keywords?: string | readonly string[];
};
export type SidebarItemCategoryLinkGeneratedIndex = {
  type: "generated-index";
  slug: string;
  permalink: string;
  title?: string;
  description?: string;
  image?: string;
  keywords?: string | readonly string[];
};

export type SidebarItemCategoryLinkConfig =
  | SidebarItemCategoryLinkDoc
  | SidebarItemCategoryLinkGeneratedIndexConfig;

export type SidebarItemCategoryLink =
  | SidebarItemCategoryLinkDoc
  | SidebarItemCategoryLinkGeneratedIndex;

// The user-given configuration in sidebars.js, before normalization
export type SidebarItemCategoryConfig = Expand<
  Optional<SidebarItemCategoryBase, "collapsed" | "collapsible"> & {
    // items: SidebarCategoriesShorthand | SidebarItemConfig[];
    items: SidebarItemConfig[];
    link?: SidebarItemCategoryLinkConfig;
  }
>;

export type SidebarCategoriesShorthand = {
  [sidebarCategory: string]: SidebarCategoriesShorthand | SidebarItemConfig[];
};

export type SidebarItemConfig =
  | Omit<SidebarItemDoc, "translatable">
  | SidebarItemHtml
  | SidebarItemLink
  | SidebarItemAutogenerated
  | SidebarItemCategoryConfig
  | string
  | SidebarCategoriesShorthand;

// export type SidebarConfig = SidebarCategoriesShorthand | SidebarItemConfig[];
export type SidebarConfig = SidebarItemConfig[];

export type SidebarsConfig = {
  [sidebarId: string]: SidebarConfig;
};
