name: 🚀 Deployer

env:
  HUSKY: 0
  NODE_VERSION: 22

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["**"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-deployer
  cancel-in-progress: false

permissions: { }

jobs:
  build:
    name: "Docs build"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Restore NPM cache
        id: npm-cache-restore
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: &build-docs-npm-cache-paths |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: |
            ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}-

      - name: Install dependencies
        run: |
          corepack enable
          npm ci

      - name: Build docs
        env:
          NEXT_TELEMETRY_DISABLED: '1'
          GITHUB_PAGES: ${{ github.event_name != 'pull_request' && 'true' || '' }}
        run: |
          npm run build
          if [ -z '${{ env.GITHUB_PAGES }}' ]; then
            nlines=20
            target='llms.txt'
            test -f "$target" && echo -e "\nFirst $nlines lines of $target" && head -$nlines "out/$target"
            target='llms-full.txt'
            test -f "$target" && echo -e "\nFirst $nlines lines of $target" && head -$nlines "out/$target"
            target='llms/foundations/tlb/overview/content.md'
            test -f "$target" && echo -e "\nFirst $nlines lines of $target" && head -$nlines "out/$target"
            target='404.html'
            test -f "$target" && echo -e "\nFirst $nlines lines of $target" && head -$nlines "out/$target"
          fi

      - name: Save NPM cache
        id: npm-cache-save
        if: steps.npm-cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: *build-docs-npm-cache-paths
          key: ${{ steps.npm-cache-restore.cache-primary-key }}

      - name: Upload GitHub Pages artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: out

  deploy:
    name: "Docs deploy"
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      # To deploy to Pages
      pages: write
      # To verify the deployment originates from an appropriate source
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
