name: 💅 Linting suite

env:
  HUSKY: 0
  NODE_VERSION: 22

on:
  pull_request:
    branches: ["**"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-linter
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  format-check:
    name: "Formatting"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: |
          corepack enable
          npm ci

      - name: Get changed MDX and Markdown files
        id: changed-files
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            **.md
            **.mdx
          separator: " "

      - name: Check formatting of MDX and Markdown files
        id: check-fmt
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          # language=JavaScript
          script: |
            const files = (process.env.ALL_CHANGED_FILES ?? '')
              .trim().split(' ').filter(Boolean).filter((it) => it.match(/\.mdx?$/) !== null);
            if (files.length === 0) {
              console.log('\nNo such files affected!');
              process.exit(0);
            }
            console.log('\nChecking formatting of the following MDX and Markdown files affected by this PR:\n');
            for (const file of files) {
              console.log(`- ${file}`);
            }
            try {
              await exec.exec('npm', ['run', 'check:fmt:some', '--', ...files], {
                silent: true, // >/dev/null 2>&1
              });
            } catch (_) {
              // Comment right in the actions output
              console.log('\n\x1b[31mError:\x1b[0m Some files are not properly formatted!');
              console.log('1. Install necessary dependencies: \x1b[31mnpm ci\x1b[0m');
              console.log(`2. Run this command to fix the issues: \x1b[31mnpm run fmt:some -- ${files.join(' ')}\x1b[0m`);

              // Rethrow the exit code of the failed formatting check
              core.setFailed('Some files are not properly formatted!');
              process.exit(1);
            }

      - name: Hide prior PR comments and issue a new one in case of failure
        if: |
          (
            !cancelled() &&
            steps.changed-files.conclusion == 'success' &&
            github.event_name == 'pull_request' &&
            (
              github.event.pull_request.head.repo.fork == false ||
              github.event.pull_request.head.repo.full_name == github.repository
            )
          )
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          SUCCESS: ${{ steps.check-fmt.conclusion == 'failure' && 'false' || 'true' }}
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          # language=JavaScript
          script: |
            const { hidePriorCommentsWithPrefix, createComment } = await import('${{ github.workspace }}/.github/scripts/common.mjs');
            const success = JSON.parse(process.env.SUCCESS ?? 'false');
            const files = (process.env.ALL_CHANGED_FILES ?? '')
              .trim().split(' ').filter(Boolean).filter((it) => it.match(/\.mdx?$/) !== null);
            const comment = [
              'To fix the **formatting** issues:\n',
              '1. Install necessary dependencises: `npm ci`',
              '2. Then, run this command:',
              '   ```shell',
              `   npm run fmt:some -- ${files.join(' ')}`,
              '   ```',
              '\nAlternatively, a maintainer can comment /fmt in this PR to auto-apply fixes in a new commit from the bot.',
            ].join('\n');
            const prefix = comment.slice(0, 30);
            await hidePriorCommentsWithPrefix({ github, context, exec, prefix, resolved: success });
            // Create a new PR comment in case of a new failure
            if (!success) {
              await createComment({ github, context, exec, body: comment });
            }

  spell-check:
    name: "Spelling"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          # The fetch-depth is not set to 0 to prevent the cspell-action
          # from misfiring on files that are in main but not on this PR branch

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: |
          corepack enable
          npm ci

      - name: Run CSpell on changed files
        # This action also annotates the PR
        uses: streetsidesoftware/cspell-action@9cd41bb518a24fefdafd9880cbab8f0ceba04d28 # 8.3.0
        with:
          check_dot_files: explicit
          suggestions: true
          config: ".cspell.jsonc"

  link-check:
    name: "Links: broken, navigation, redirects"
    runs-on: ubuntu-latest
    env:
      ALLOW_NET: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: |
          corepack enable
          npm ci

      # Broken

      - name: Check broken links
        if: ${{ !cancelled() }}
        run: npm run check:links

      # Navigation

      - name: Check uniqueness of navigation paths in docs.json
        if: ${{ !cancelled() }}
        run: npm run check:navigation -- unique

      - name: Check existence of navigation .mdx pages in docs.json
        if: ${{ !cancelled() }}
        run: npm run check:navigation -- exist

      - name: Check coverage of .mdx pages by docs.json
        if: ${{ !cancelled() }}
        run: npm run check:navigation -- cover

      # Redirects

      - name: Check uniqueness of redirect sources in docs.json
        if: ${{ !cancelled() }}
        run: npm run check:redirects -- unique

      - name: Check existence of redirect destinations in docs.json
        if: ${{ !cancelled() }}
        run: npm run check:redirects -- exist

      - name: Check redirects against the previous TON Documentation
        if: ${{ !cancelled() }}
        run: npm run check:redirects -- previous

      - name: Check redirects against the upstream docs.json structure
        if: ${{ !cancelled() }}
        run: npm run check:redirects -- upstream
